USE [DSSPPROD_Search_AnalyticsReportingStore]
GO

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT 
      [AggregationLevel]
      ,[ItemUri]
      ,[TotalHitsCount]
      ,[TotalUUsCount]
      ,[LastProcessingTime]
      ,[LastProcessingHitsCount]
      ,[LastProcessingUUsCount]
      ,[Day00Hits]
      ,[Day00UUs]
      ,[Day01Hits]
      ,[Day01UUs]
      ,[Day02Hits]
      ,[Day02UUs]
      ,[Day03Hits]
      ,[Day03UUs]
      ,[Day04Hits]
      ,[Day04UUs]
      ,[Day05Hits]
      ,[Day05UUs]
      ,[Day06Hits]
      ,[Day06UUs]
      ,[Day07Hits]
      ,[Day07UUs]
      ,[Day08Hits]
      ,[Day08UUs]
      ,[Day09Hits]
      ,[Day09UUs]
      ,[Day10Hits]
      ,[Day10UUs]
      ,[Day11Hits]
      ,[Day11UUs]
      ,[Day12Hits]
      ,[Day12UUs]
      ,[Day13Hits]
      ,[Day13UUs]
      ,[Day14Hits]
      ,[Day14UUs]
  FROM [DSSPPROD_Search_AnalyticsReportingStore].[dbo].[AnalyticsItemData]
  WHERE ItemUri LIKE 'https%'
  ORDER BY TotalHitsCount DESC